apiVersion: v1
kind: Pod
metadata:
  name: pod-with-config-map
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: cm-from-file
      env:
        # Define the environment variable
        - name: RENAMED_VARIABLE
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: cm-sample
              # Specify the key associated with the value
              key: KEY2
