apiVersion: v1
kind: Pod
metadata:
  name: busybox-w-secrets-from-k8s-secret
  namespace: kv-ns
spec:
  containers:
    - name: busybox
      image: k8s.gcr.io/e2e-test-images/busybox:1.29
      command:
        - "/bin/sleep"
        - "10000"
      volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      env:
      - name: POD_SECRET_FROM_k8S_SECRET_1
        valueFrom:
          secretKeyRef:
            name: k8s-secret
            key: k8s-secret-1
      - name: POD_SECRET_FROM_k8S_SECRET_2
        valueFrom:
          secretKeyRef:
            name: k8s-secret
            key: k8s-secret-2
      securityContext:
        capabilities:
          drop:
            - NET_RAW
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: secret-provider-to-k8s-secrets
