apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "987bf453-bdf6-44f0-9bfe-ca05a6a490f3"
    keyvaultName: "kv-akscni-prod"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: ExamplePassword                                                                                                         
          objectType: secret                                                
          objectVersion: ""
        - |
          objectName: MySecret                                                                                                         
          objectType: secret                                                
          objectVersion: ""
    tenantId: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
