apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-provider-to-k8s-secrets
  namespace: kv-ns
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "########-####-####-####-############"
    keyvaultName: "kv-confidential-qa"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: kv-secret-1
          objectType: secret
          objectVersion: ""
        - |
          objectName: kv-secret-2
          objectType: secret
          objectVersion: ""
    tenantId: "############-####-####-####-############"
  secretObjects:
  - data:
    - key: k8s-secret-1                             # key to reference the secret from the k8s secret object
      objectName: kv-secret-1                       # name of the mounted content to sync; this could be the object name or the object alias (kv secret name)
    - key: k8s-secret-2                             # key to reference the secret from the k8s secret object
      objectName: kv-secret-2                       # name of the mounted content to sync; this could be the object name or the object alias (kv secret name)
    secretName: k8s-secret                          # name of the Kubernetes secret object
    type: Opaque                                    # type of Kubernetes secret object (for example, Opaque, kubernetes.io/tls)
