apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-secret-provider
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "########-####-####-####-############"
    keyvaultName: "kv-confidential-qa"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: ExamplePassword
          objectType: secret
          objectVersion: ""
        - |
          objectName: MySecret
          objectType: secret
          objectVersion: ""
    tenantId: "############-####-####-############"
