apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-provider-to-pod-volumes
  namespace: kv-ns
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "########-####-####-####-############"
    keyvaultName: "kv-confidential-qa"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: kv-secret-1
          objectType: secret
          objectVersion: ""
        - |
          objectName: kv-secret-2
          objectType: secret
          objectVersion: ""
    tenantId: "############-####-####-####-############"
