apiVersion: v1
kind: Pod
metadata:
  name: pod-security-context-at-container-lvl
  namespace: default
spec:
  containers:
    - name: nginx-container
      image: nginx
      securityContext:
        capabilities:
          add: ["NET_ADMIN", "SYS_TIME"]
