apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: secret-provider-pod-managed
  namespace: kv-demo
spec:
  provider: azure
  secretObjects:
    - data:
        - key: foo
          objectName: secret1
        - key: bar
          objectName: secret2
      secretName: secret-provider-secrets
      type: Opaque
  parameters:
    usePodIdentity: "true"
    keyvaultName: "kv-confidential-prod"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: ExamplePassword                                                                                                         
          objectType: secret                                                
          objectVersion: ""
        - |
          objectName: MySecret                                                                                                         
          objectType: secret                                                
          objectVersion: ""
        - |
          objectName: secret1                                                                                                         
          objectType: secret                                                
          objectVersion: ""
        - |
          objectName: secret2                                                                                                         
          objectType: secret                                                
          objectVersion: ""
    tenantId: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
