apiVersion: v1
kind: Pod
metadata:
  name: pod-managed-id-to-aks-vmss
  namespace: $aks_vmss_ns
  labels:
    aadpodidbinding: $aks_vmss_pod_identity
spec:
  containers:
    - name: container-managed-id-to-aks-vmss
      image: mcr.microsoft.com/oss/azure/aad-pod-identity/demo:v1.6.3
      args:
        - --subscriptionid=$SUBSCRIPTION_ID
        - --clientid=$IDENTITY_CLIENT_ID_TO_AKS_VMSS
        - --resourcegroup=$app_rg
      securityContext:
        capabilities:
          drop:
            - NET_RAW
      env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
  nodeSelector:
    kubernetes.io/os: linux
