apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
    - image: busybox
      name: myapp
      args:
        - sleep
        - 1d
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
