# kubectl run nginx-alpine --image nginx:alpine -o yaml --dry-run=client > pod-nginx-alpine.yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-alpine
  name: nginx-alpine
spec:
  containers:
    - image: nginx:alpine
      name: nginx-alpine
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
