apiVersion: v1
kind: Pod
metadata:
  name: nginx-w-env
  namespace: default
  labels:
    app: myapp
spec:
  containers:
    - name: nginx-container
      image: nginx
      env:
        - name: MY_ENV_KEY
          value: MY_ENV_VAL
