apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
    netpol: allow
spec:
  containers:
    - image: busybox
      name: busybox
      args:
        - sleep
        - 1d
  restartPolicy: Never
